
name: Publish
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - run: npm install
            - run: npm run build
            - run: |
                 echo @sankshaypusa:https://npm.pkg.github.com/> /Users/sankshay/Downloads/E-commerceplatform_using_typescript/server/9-jobber-shared/src/.npmrc
                 echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> /Users/sankshay/Downloads/E-commerceplatform_using_typescript/server/9-jobber-shared/src/.npmrc
            - run: npm publish
              working-directory: ./build
              env:
                NPM_TOKEN: ${{ secrets.GITHUB_TOKEN}}

